# image will be published to ghcr.io/<user>/<name>
name: lwl-os
# description will be included in the image's metadata
description: Custom distro built for laptops from Laptop With Linux.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-nvidia
image-version: 40

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://comexr.github.io/comexr.repo
    keys:
      - https://comexr.github.io/comexr.asc
    install:
      - age #Needed for chezmoi encryption
      - expect #Interactive prompts automation
      - grubby #Tool to update grub parameters (used by selinux.sh)
      - hidapi #Dependency for BIOS updates
      - lwl-drivers
      - PackageKit #Dependency for cosmic-store
      - zenity #Interactive prompts
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Evolution
      remove:

  - type: chezmoi
    # Git repository to initialize
    repository: "https://github.com/comexr/dotfiles" # Required - Default: n/a  - Expects type: string
    # # Whether to enable the modules services globally for all users, if false users need to enable services manually
    # all-users: true # Optional - Default: true - Expects type: boolean
    # # Dotfiles will be updated with this interval
    # run-every: '1d' # Optional - Default: '1d' - Expects type: string
    # # Dotfile updates will wait this long after a boot before running
    # wait-after-boot: '5m' # Optional - Default: '5m' - Expects type: string
    # # Disable the service that initializes `repository` on users that are logged in or have linger enabled
    # disable-init: false # Optional - Default: false - Expects type: boolean
    # # Disable the timer that updates chezmoi with the interval set above
    # disable-update: false # Optional - Default: false - Expects type: boolean
    # # What to do when file different that exists on your repo is has been changed or exists locally. Accepts "skip" or "replace"
    # file-conflict-policy: "skip" # Optional - Default: "skip" - Expects type: string

  - type: yafti

  - type: script
    snippets:
      - "git config --system user.email 'info@comexr.com' && git config --system user.name 'comexr'" #Set GitHub config options (in /etc/gitconfig)
      #- "sudo grubby --update-kernel ALL --args selinux=0" #Temporarily disable SELinux